{{ $defaults := .Values.defaults -}}
---
{{ range $applications := .Values.applications -}}
---
{{- if $applications.gitopsCreate }}
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "{{ $applications.apmnum }}-project"
  namespace: application-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  sourceNamespaces:
  - "{{ $applications.apmnum }}-{{ $applications.appserviceNumber }}-team"
  description: "{{ $applications.apmnum }} users project"
  sourceRepos:
  {{ toYaml $applications.appProject.repos | nindent 2 }}
  clusterResourceWhitelist:
  - group: '*'
    kind: Namespace
  {{- if $applications.appProject.clusterResourceWhitelist }}
  {{ toYaml $applications.appProject.clusterResourceWhitelist | nindent 2 }}
  {{- end }}
  destinations:
  - namespace: "{{ $applications.apmnum }}-{{ $applications.appserviceNumber }}}*"
    server: 'https://kubernetes.default.svc'
  {{- if $applications.appProject.destinations }}
  {{ toYaml $applications.appProject.destinations | nindent 2 }}
  {{- end }}
  roles:
  {{- if $applications.appProject.roles }}
  {{ toYaml $applications.appProject.roles | nindent 2 }}
  {{- else }}
  - name: 'all-app-actions'
    description: Application privliges to my-project
    policies:
    - p, proj:{{ $applications.apmnum }}-{{ $applications.appserviceNumber }}-project:all-app-actions, applications, *, {{ $applications.apmnum }}-{{ $applications.appserviceNumber }}-project/*, allow
    - p, proj:{{ $applications.apmnum }}-{{ $applications.appserviceNumber }}-project:all-app-actions, applicationssets, *, {{ $applications.apmnum }}-{{ $applications.appserviceNumber }}-project/*, allow
    groups:
    - {{ $applications.appProject.adGroup }}
    {{- end }}
  {{- end }}
{{- end }}