{{ range $applications := .Values.applications -}}
---
{{- if $applications.gitopsCreate }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $applications.apmnum }}-{{ $applications.appserviceNumber }}-team
  annotations:  
  {{- if $applications.annotations }}
    {{- toYaml $applications.annotations | trimPrefix "|" | indent 2 }}
  {{ end }}
  labels:
    {{- if $applications.labels }}
      {{- toYaml $applications.labels | trimPrefix "|" | indent 2 }}
    {{ end }}
  {{- end }}
{{- end }}