# OpenShift Lightspeed Operator Configuration
appTeam: lightspeed-operator

# Sync wave for ArgoCD deployment
syncwave: 1

# Operator configuration
operatorName: lightspeed-operator
operatorNamespace: openshift-lightspeed
operatorChannel: stable
operatorSource: redhat-operators
operatorSourceNamespace: openshift-marketplace
operatorInstallPlanApproval: Manual

# OLSConfig configuration
olsConfig:
  enabled: true
  name: cluster
  llm:
    providers:
      - name: openai
        type: openai
        url: https://api.openai.com/v1
        credentialsSecretRef:
          name: openai-api-keys
        models:
          - name: gpt-3.5-turbo
          - name: gpt-4
  ols:
    conversationCache:
      type: memory
    logLevel: INFO
    queryFilters:
      - name: no_cluster_specific
        pattern: "(?i)\\b(cluster|node)\\s+\\w+"
        replaceWith: "cluster"

# Helper status checker dependency
helper-status-checker:
  enabled: true
  approver: true
  checks:
    - operatorName: lightspeed-operator
      subscriptionName: lightspeed-operator
      namespace:
        name: openshift-lightspeed
      syncwave: 2
      serviceAccount:
        name: "lightspeed-install-check"
