{{- if .Values.lokiStack.enabled }}
apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: {{ .Values.lokiStack.name }}
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.syncwave }}"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  size: {{ .Values.lokiStack.size }}
  {{- if .Values.lokiStack.storage }}
  storage:
    schemas:
    - version: v12
      effectiveDate: "2022-06-01"
    {{- if .Values.objectStorage.s3.enabled }}
    secret:
      name: {{ .Values.objectStorage.s3.secret.name }}
      type: s3
    {{- else }}
    secret:
      name: {{ .Values.lokiStack.name }}-storage
      type: filesystem
    {{- end }}
    {{- if .Values.lokiStack.storage.storageClassName }}
    storageClassName: {{ .Values.lokiStack.storage.storageClassName }}
    {{- end }}
    {{- if .Values.lokiStack.storage.size }}
    size:
      {{- toYaml .Values.lokiStack.storage.size | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- if .Values.lokiStack.limits }}
  limits:
    {{- toYaml .Values.lokiStack.limits | nindent 4 }}
  {{- end }}
  {{- if .Values.lokiStack.tenants }}
  tenants:
    mode: {{ .Values.lokiStack.tenants.mode }}
    {{- if .Values.lokiStack.tenants.authentication }}
    authentication:
      {{- toYaml .Values.lokiStack.tenants.authentication | nindent 6 }}
    {{- end }}
  {{- end }}
  {{- if .Values.lokiStack.rules }}
  rules:
    enabled: {{ .Values.lokiStack.rules.enabled }}
    {{- if .Values.lokiStack.rules.selector }}
    selector:
      {{- toYaml .Values.lokiStack.rules.selector | nindent 6 }}
    {{- end }}
    {{- if .Values.lokiStack.rules.namespaceSelector }}
    namespaceSelector:
      {{- toYaml .Values.lokiStack.rules.namespaceSelector | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end }}
