{{- if and .Values.lokiStack.enabled .Values.uiPlugin.enabled }}
apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: {{ .Values.uiPlugin.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.syncwave }}"
spec:
  displayName: {{ .Values.uiPlugin.displayName | quote }}
  service:
    name: {{ .Values.uiPlugin.service.name }}
    namespace: {{ .Values.uiPlugin.service.namespace | default "openshift-logging" }}
    port: {{ .Values.uiPlugin.service.port }}
    basePath: {{ .Values.uiPlugin.service.basePath | quote }}
  proxy:
    - type: Service
      alias: lokistack-gateway
      authorize: {{ .Values.uiPlugin.proxy.authorize }}
      service:
        name: {{ .Values.uiPlugin.proxy.service.name }}
        namespace: {{ .Values.uiPlugin.proxy.service.namespace | default "openshift-logging" }}
        port: {{ .Values.uiPlugin.proxy.service.port }}
{{- end }}

