# Chart Releaser configuration
# This ensures chart-releaser only processes the specific chart in the matrix
owner: rosa-hcp-dedicated-vpc
git-repo: helm-repository
charts-repo-url: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
index-path: index.yaml
packages-with-index: true
skip-existing: true
