{{- if .Values.openshiftGitops.initialRepositories }}
{{- range $repo := .Values.openshiftGitops.initialRepositories }}
{{- range $ns := $.Values.openshiftGitops.namespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $repo.name }}
  namespace: {{ $ns }}
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "2"
stringData:
  type: {{ $repo.type }}
  url: {{ $repo.url }}
{{- end }}
{{- end }}
{{- end }}