{{- if .Values.openshiftGitops.repositoryCredentials }}
{{- range $cred := .Values.openshiftGitops.repositoryCredentials }}
{{- range $ns := $.Values.openshiftGitops.namespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $cred.name }}
  namespace: {{ $ns }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  username:  {{ $cred.username | quote }}
  password: {{ $cred.password | quote }}
  type: {{ $cred.type }}
  url: {{ $cred.url }}
{{- end }}
{{- end }}
{{- end }}