apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crd-reader
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - 'customresourcedefinitions'
  verbs:
  - get
  - list
{{- if .Values.openshiftGitops.namespaces }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-reader-binding
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crd-reader
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .Values.openshiftGitops.namespaces | first }}
{{- end }}
