{{- if .Values.openshiftGitops.namespaces }}
{{- range $index, $ns := .Values.openshiftGitops.namespaces }}
{{- if and (ne $ns "openshift-gitops") (ne $ns "olm") }}
---
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    "openshift.io/description": ""
    "openshift.io/display-name": ""
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
  labels:
    kubernetes.io/metadata.name: {{ $ns }}
    openshift.io/cluster-monitoring: "true"
  name: {{ $ns }}
spec:
  finalizers:
  - kubernetes
{{- end }}
{{- end }}
{{- end }}
