{{- if .Values.openshiftGitops.secrets }}
{{- range $secret := .Values.openshiftGitops.secrets }}
{{- range $ns := $.Values.openshiftGitops.namespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $ns }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
    {{- if eq $secret.type "repo-creds" }}
    argocd.argoproj.io/secret-type: repo-creds
    {{- end }}
type: kubernetes.io/basic-auth
stringData:
  username:  {{ $secret.username | quote }}
  password: {{ $secret.password | quote }}
  {{- if eq $secret.type "repo-creds" }}
  type: git
  url: https://github.com/demo-setup-test
  {{- end }}
{{- end }}
{{- end }}
{{- end }}