{{- if .Values.openshiftGitops.enabled }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.openshiftGitops.subscription.spec.name }}
  namespace: {{ .Values.openshiftGitops.subscription.namespace }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-5"
spec:
  channel: {{ .Values.openshiftGitops.subscription.spec.channel }}
  installPlanApproval: {{ .Values.openshiftGitops.subscription.installPlanApproval }}
  name: {{ .Values.openshiftGitops.subscription.spec.name }}
  source: {{ .Values.openshiftGitops.subscription.spec.source | default "redhat-operators" | quote }}
  sourceNamespace: {{ .Values.openshiftGitops.subscription.spec.sourceNamespace | default "openshift-marketplace" | quote }}
  config:
    env:
    - name: DISABLE_DEFAULT_ARGOCD_INSTANCE
      value:  {{ .Values.openshiftGitops.subscription.disableDefaultArgoCD | quote }}
{{- end }}
