apiVersion: v2
name: rhods-operator
description: Master chart to deploy and configure the RHODS Operator (Red Hat OpenShift Data Science)
version: 1.2.8
home: https://github.com/rosa-hcp-dedicated-vpc/helm-repository
dependencies:
  - name: helper-operator
    version: ~1.1.0
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
  - name: helper-status-checker
    version: 4.3.7
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
    condition: helper-status-checker.enabled
maintainers:
  - name: Paul Foster
    email: pafoster@redhat.com
    url: https://github.com/rosa-hcp-dedicated-vpc
sources:
  - https://github.com/rosa-hcp-dedicated-vpc/helm-repository
keywords:
  - ai
  - machine-learning
  - openshift-ai
  - data-science
annotations:
  artifacthub.io/license: Apache-2.0
