{{- with .Values }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: installplan-approver
  namespace: {{ .namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-4"
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - installplans
      - subscriptions
    verbs:
      - get
      - list
      - patch
{{- end }}
