{{- with .Values }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: installplan-approver-job
  namespace: {{ .namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-4"
{{- end }}
