{{- $pipelinesUsesOperatorHub := and .Values.openshiftPipelines.enabled (eq .Values.openshiftPipelines.subscription.spec.source "operatorhubio-catalog") }}
{{- $gitopsUsesOperatorHub := and .Values.openshiftGitops.enabled (eq .Values.openshiftGitops.subscription.spec.source "operatorhubio-catalog") }}
{{- $shouldCreate := or $pipelinesUsesOperatorHub $gitopsUsesOperatorHub }}


{{- if $shouldCreate }}
{{- $existing := lookup "operators.coreos.com/v1alpha1" "CatalogSource" "olm" "operatorhubio-catalog" -}}
{{- if not $existing }}
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: operatorhubio-catalog
  namespace: olm
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-8"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  sourceType: grpc
  image: quay.io/operator-framework/upstream-community-operators:latest
  displayName: OperatorHub.io Catalog
  publisher: OperatorHub.io
{{- end }}
{{- end }}
