# NVIDIA GPU Operator Configuration
appTeam: nvidia-gpu-operator

# Sync wave for ArgoCD deployment
syncwave: 0

# Operator configuration
operatorName: gpu-operator-certified
operatorNamespace: nvidia-gpu-operator
operatorChannel: stable
operatorSource: certified-operators
operatorSourceNamespace: openshift-marketplace
operatorInstallPlanApproval: Manual

# ClusterPolicy configuration
clusterPolicy:
  enabled: true
  name: gpu-cluster-policy
  # Operator configuration (NFD managed separately)
  operator:
    defaultRuntime: crio
  # NVIDIA Driver - REQUIRED
  driver:
    enabled: true
  # NVIDIA Container Toolkit - REQUIRED
  toolkit:
    enabled: true
  # Device Plugin - enables nvidia.com/gpu resource
  devicePlugin:
    enabled: true
  # DCGM (Data Center GPU Manager) - REQUIRED
  dcgm:
    enabled: true
  # DCGM Exporter for monitoring
  dcgmExporter:
    enabled: true
  # GPU Feature Discovery
  gfd:
    enabled: true
  # Additional components - matching UI defaults
  migManager:
    enabled: true
  nodeStatusExporter:
    enabled: true
  gds:
    enabled: false
  cdi:
    enabled: false
  vgpuManager:
    enabled: false
  vgpuDeviceManager:
    enabled: true
  sandboxWorkloads:
    enabled: false
  vfioManager:
    enabled: true

# Helper status checker dependency
helper-status-checker:
  enabled: true
  approver: true
  checks:
    - operatorName: gpu-operator-certified
      subscriptionName: gpu-operator-certified
      namespace:
        name: nvidia-gpu-operator
      serviceAccount:
        name: "gpu-install-check"
    - operatorName: nfd
      subscriptionName: nfd
      namespace:
        name: openshift-nfd
      serviceAccount:
        name: "gpu-nfd-install-check"
