---
apiVersion: v1
kind: Secret
metadata:
  name: aws-efs-cloud-credentials
  namespace: openshift-cluster-csi-drivers
  annotations:
stringData:
  credentials: |-
    [default]
    role_arn = {{ .Values.roleArn }}
    web_identity_token_file = /var/run/secrets/openshift/serviceaccount/token
---
apiVersion: operator.openshift.io/v1
kind: ClusterCSIDriver
metadata:
  name: efs.csi.aws.com
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncwave | default 3 | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  managementState: Managed
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncwave | default 3 | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
allowVolumeExpansion: true
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{ .Values.fileSystemId }}
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
  basePath: "/dynamic_provisioning"
