---
apiVersion: v1
kind: Secret
metadata:
  name: aws-efs-cloud-credentials
  namespace: openshift-cluster-csi-drivers
  annotations:
stringData:
  credentials: |-
    [default]
    role_arn = {{ .Values.roleArn }}
    web_identity_token_file = /var/run/secrets/openshift/serviceaccount/token
---
apiVersion: operator.openshift.io/v1
kind: ClusterCSIDriver
metadata:
  name: efs.csi.aws.com
spec:
  managementState: Managed

