# Using sub-chart helper-installplan-approver
helper-status-checker:
  approver: true
  enabled: true
  checks:
    - operatorName: rhacs-operator
      subscriptionName: rhacs-operator
      namespace:
        name: rhacs-operator
      serviceAccount:
        name: "status-checker"
# startingCSV: rhacs-operator.v4.7.4
helper-operator:
  enabled: true
  operators:
    rhacs-operator:
      enabled: true
      namespace:
        name: rhacs-operator
      subscription:
        channel: stable 
        approval: Manual
        operatorName: rhacs-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: true
        notownnamespace: true

# apiVersion: operators.coreos.com/v1alpha1
# kind: Subscription
# metadata:
#   creationTimestamp: "2025-07-07T03:21:04Z"
#   generation: 1
#   labels:
#     operators.coreos.com/rhacs-operator.rhacs-operator: ""
#   name: rhacs-operator
#   namespace: rhacs-operator
#   resourceVersion: "77222"
#   uid: c092ec60-6caf-4ed2-84f4-160398887048
# spec:
#   channel: stable
#   installPlanApproval: Automatic
#   name: rhacs-operator
#   source: redhat-operators
#   sourceNamespace: openshift-marketplace
#   startingCSV: rhacs-operator.v4.7.4