{{- if .Values.hyperConverged.create }}
apiVersion: hco.kubevirt.io/v1beta1
kind: HyperConverged
metadata:
  name: {{ .Values.hyperConverged.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.hyperConverged.syncWave }}"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,Validate=false
spec:
  # Basic configuration for OpenShift Virtualization
  infra: {}
  workloads: {}
  
  # Feature gates and configuration
  featureGates:
    enableCommonBootImageImport: true
    deployTektonTaskResources: false
    
  # Storage configuration
  storageImport:
    
  # Live migration configuration
  liveMigrationConfig:
    bandwidthPerMigration: "64Mi"
    completionTimeoutPerGiB: 800
    parallelMigrationsPerCluster: 5
    parallelOutboundMigrationsPerNode: 2
    progressTimeout: 150
    
  # Resource requirements (optional - can be customized)
  resourceRequirements:
    vmiCPUAllocationRatio: 10
{{- end }}
