dependencies:
  - name: helper-status-checker
    version: 4.1.2
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
  - name: helper-operator
    version: 1.0.29
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
name: cluster-efs
version: 0.2.6
apiVersion: v2
description: Chart to deploy the efs operator and supporting componenets
