# Using sub-chart helper-installplan-approver
helper-status-checker:
  approver: true
  enabled: true
  checks:
    - operatorName: aws-efs-csi-driver-operator
      subscriptionName: aws-efs-csi-driver-operator
      namespace:
          name: openshift-cluster-csi-drivers
      serviceAccount:
        name: "status-checker"
helper-operator:
  enabled: true
  operators:
    aws-efs-csi-driver-operator:
      enabled: true
      namespace:
        name: openshift-cluster-csi-drivers
      subscription:
        channel: stable 
        approval: Manual
        operatorName: aws-efs-csi-driver-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: true
# roleArn, fileSystemId, csv is pulled in via the Cluster/non-prod/high-trust/<clster_name>/infrastructure.yaml
roleArn: 
fileSystemId: 
csv:

