apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.operatorNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.syncwave }}"
  labels:
    openshift.io/cluster-monitoring: "true"
