{{- if .Values.olsConfig.enabled }}
{{- range .Values.olsConfig.llm.providers }}
{{- if .credentialsSecretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .credentialsSecretRef.name }}
  namespace: {{ $.Values.operatorNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ $.Values.syncwave }}"
type: Opaque
stringData:
  apitoken: "not-required"
---
{{- end }}
{{- end }}
{{- end }}
