{{- if .Values.olsConfig.enabled }}
{{- range .Values.olsConfig.llm.providers }}
{{- if .credentialsSecretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .credentialsSecretRef.name }}
  namespace: {{ $.Values.operatorNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ $.Values.syncwave }}"
type: Opaque
data:
  # Add your API key here (base64 encoded)
  # Example: api_key: <base64-encoded-api-key>
  api_key: ""
---
{{- end }}
{{- end }}
{{- end }}
