apiVersion: logging.openshift.io/v1alpha1
kind: LogFileMetricExporter
metadata:
  name: vector-metric-exporter
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncwave | default 3 | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,Validate=false
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  resources:
    limits:
      cpu: 500m
    requests:
      cpu: 200m
      memory: 128Mi