---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: logging-collector
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncwave | default 3 | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    eks.amazonaws.com/role-arn: {{ .Values.roleArn | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: collect-infrastructure-logs
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncwave | default 3 | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collect-infrastructure-logs
subjects:
- kind: ServiceAccount
  name: logging-collector
  namespace: openshift-logging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: collect-application-logs
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncwave | default 3 | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: collect-application-logs
subjects:
- kind: ServiceAccount
  name: logging-collector
  namespace: openshift-logging
---