apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::319668183582:role/the-cluster-openshift-logging-cloudwatch-role
  name: logging
  namespace: openshift-logging