apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: rhsso-backstage
    app.kubernetes.io/instance: rhsso-backstage
    app.kubernetes.io/name: rhsso-backstage
  name: backstage
spec:
  realmSelector:
    matchLabels:
      app: rhsso-backstage
      app.kubernetes.io/instance: rhsso-backstage
      app.kubernetes.io/name: rhsso-backstage
  client:
    clientAuthenticatorType: client-secret
    clientId: backstage
    defaultClientScopes:
    - profile
    - email
    - roles
    directAccessGrantsEnabled: true
    implicitFlowEnabled: false
    publicClient: false
    standardFlowEnabled: true
    redirectUris:
{{- range .Values.client.redirectUri }}
      - {{ . | quote }}
{{- end }}