apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: backstage
  labels:
    app: rhsso-backstage
    app.kubernetes.io/instance: rhsso-backstage
    app.kubernetes.io/name: rhsso-backstage
  annotations:
    avp.kubernetes.io/path: "{{ .Values.clientSecret }}"
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  instanceSelector:
    matchLabels:
      app: rhsso-backstage
      app.kubernetes.io/instance: rhsso-backstage
      app.kubernetes.io/name: rhsso-backstage
  realm:
    displayName: Backstage Authentication Realm
    enabled: true
    id: backstage
    realm: backstage
    identityProviders:
      - alias: GitHub
        providerId: github
        config: 
          clientId: <path:{{ .Values.clientSecret }}#clientId>
          clientSecret: <path:{{ .Values.clientSecret }}#clientSecret>
          defaultScopes: user:email read:user


