apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.project.name }}
  annotations:
    openshift.io/comments: {{ .Values.project.annotations.comments }}
    openshift.io/description: {{ .Values.project.annotations.description }}
    openshift.io/display-name: {{ .Values.project.annotations.display_name }}
  labels:
    domain: {{ .Values.project.labels.domain | quote }}
    egressip: {{ .Values.project.labels.egressip | quote }}
    ingress: {{ .Values.project.labels.ingress | quote }}
    primary-owner: {{ .Values.project.labels.primary_owner | quote }}
    zone: {{ .Values.project.labels.zone | quote }}
    {{- include "namespaces.labels" . | nindent 4 }}
