kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.project.name }}-networkpolicy
  namespace: {{ .Values.project.name }}
  annotations:
    app.kubernetes.io/managed-by: argo-git
  labels:
    {{- include "namespaces.labels" . | nindent 4 }}
spec:
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            network.openshift.io/policy-group: ingress
  podSelector: {}
  policyTypes:
  - Ingress
