apiVersion: v2
name: model-mistral
description: Helm chart for deploying AI models using KServe and vLLM
type: application
version: 0.1.3
appVersion: "1.0"
dependencies:
  - name: helper-status-checker
    version: 4.1.8
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
    condition: helper-status-checker.enabled