---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-2"
  labels:
  name: operator-install-job-hook-aws-pca
rules:
- apiGroups:
  - operators.coreos.com
  resources:
  - clusterserviceversions
  verbs:
  - get
  - list
  - create
  - update
  - patch
  - delete
- apiGroups:
  - "*"
  resources:
  - pods
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-2"
  labels:
  name: operator-install-job-hook-aws-pca
  namespace: cert-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: operator-install-job-hook-aws-pca
subjects:
- kind: ServiceAccount
  name: operator-install-job-hook-aws-pca
  namespace: cert-manager
---
apiVersion: v1
imagePullSecrets:
kind: ServiceAccount
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-1"
  name: operator-install-job-hook-aws-pca
  namespace: cert-manager
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: hook-succeeded
    helm.sh/hook-weight: "2"
  name: operator-install-job-hook-aws-pca
  namespace: cert-manager
spec:
  template:
    spec:
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccount: operator-install-job-hook-aws-pca
      serviceAccountName: operator-install-job-hook-aws-pca
      terminationGracePeriodSeconds: 30
      containers:
        - name: operator-install-job-hook-aws-pca
          image: registry.redhat.io/openshift4/ose-cli:latest
          imagePullPolicy: IfNotPresent
          env:
          - name: SLEEP
            value: "5"
          command:
            - /bin/bash
            - -c
            - |
              # openshift-cert-manager
              echo "checking on cert manager pods"
              PODS=0
              while [ "$PODS" -ne 3 ]; do
              PODS=$(oc get pods -n cert-manager|grep -i cert-manager|grep -i 1/1|wc -l|sed 's/ //g')
              echo "Waiting for pods to come up for cert manager. PODS = $PODS"
              sleep 5
              done

