apiVersion: v1
kind: Service
metadata:
  name: {{ include "aws-privateca-issuer.fullname" . }}
  namespace: {{ .Values.nameSpace }}
  labels:
    {{- include "aws-privateca-issuer.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-1"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "aws-privateca-issuer.selectorLabels" . | nindent 4 }}
