apiVersion: v1
kind: Namespace
metadata:
  annotations:
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    openshift.io/display-name: 'backstage'
  labels:
    app: backstage
  name: backstage
