# Serverless Operator Configuration
appTeam: serverless-operator

# Sync wave for ArgoCD deployment
syncwave: 1

# Helper operator dependency
helper-operator:
  operators:
    serverless-operator:
      enabled: true
      syncwave: '0'
      namespace:
        name: openshift-serverless
        create: true
      subscription:
        channel: stable
        approval: Manual
        operatorName: serverless-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace
      operatorgroup:
        create: true
        notownnamespace: true

# Helper status checker dependency
helper-status-checker:
  enabled: true
  approver: true
  checks:
    - operatorName: serverless-operator
      subscriptionName: serverless-operator
      namespace:
        name: openshift-serverless
      serviceAccount:
        name: "serverless-install-check"