apmnum: "5678"
# #################################################################
# # default Values for gitops-payload helm chart
# #################################################################
defaults:
  # argcod application defaults
  finalizers: resources-finalizer.argocd.argoproj.io
  gitopsNamespace: openshift-gitops
  # Helm defaults
  helmRepoUrl: https://rosa-hcp-dedicated-vpc.github.io/helm-repository
  path: charts
  # Vault plugin defaults.
  plugin: false
  AWS_REGION: "ap-southeast-2"
  AVP_TYPE: "awssecretsmanager"
  # namespaces chart defaults
  chart: namespaces
  targetRevision: 1.4.8
  # ecr role
  ecrUpdateRole: arn:aws:iam:::role/rosa-ecr-access-role
  # Must set annoataions even if you do not have anything undermneath it. These apply to the project
  annotations:
    comments: "acounting teams namespaces dev only"
    description: "accounting namespaces"
    display_name: "accounting template"
  # Must set labels even if you do not have anything undermneath it. These apply to the project
  labels:
    domain: "Infrastruture_and_Cloud"
    primary_owner: "Paul.foster@redhat.com"
    quota: "resourcequota"
    region: "NoNodeSelector"
    ingress: customer-ingress
    egressip: "0.0.0.1"
  # Must set groupname even if you do not have anything undermneath it.
  groupname:
    admin_group: pa_admins
  # Must set resourceQuota even if you do not have anything undermneath it.
  resourceQuota:
  serviceAccount:
    create: true
    automount: true
    name: "pipeline"

# #################################################################
# # NAMESPACE CREATION 
# #################################################################
namespaces:
- name: accounting-ns-dev
  annotations:
  labels:
    dynatrace: true
  groupname:
  resourceQuota:
    limits_cpu: "250m"
    limits_memory: "1Gi"
    requests_cpu: "200m"
    requests_memory: "500Mi"
    persistentvolumeclaims: "5"
    limits_ephemeral_storage: "4Gi"
    pods: "50"
- name: accounting-ns-test
  annotations:
  labels:
    dynatrace: true
  groupname:
  resourceQuota:
    limits_cpu: "250m"
    limits_memory: "1Gi"
    requests_cpu: "200m"
    requests_memory: "500Mi"
    persistentvolumeclaims: "5"
    limits_ephemeral_storage: "4Gi"
    pods: "50"