apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.compliance.scansettingbinding.syncwave | quote }}
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  labels:
    app: cpaas-compliance-results
  name: cpaas-compliance-results
  namespace: {{ .Values.compliance.namespace.name | default "openshift-compliance" }}
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cpaas-compliance-results
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cpaas-compliance-results
    spec:
      containers:
      - command:
        - sleep
        - infinity
        image: 730335292448.dkr.ecr.ap-southeast-2.amazonaws.com/cpaas-codefresh-image:latest
        imagePullPolicy: IfNotPresent
        name: cpaas-compliance-results
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data
          name: ocp4-cis-node-worker
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: ocp4-cis-node-worker
        persistentVolumeClaim:
          claimName: ocp4-cis-node-worker
