# project:
#   name: "payments-ns-dev"
#   apmnum: "1234"
#   appserviceNumber: "5678"
#   ecrUpdateRole: arn:aws:iam:::role/poc-rosa-ecr-access-role
#   annotations:
#     comments: payments teams namespaces dev only
#     description: paymernts namespaces
#     display_name: namespace stemplate
#   labels:
#     domain: Infrastruture_and_Cloud
#     egressip: 0.0.0.1
#     ingress: customer-ingress
#     primary_owner: pafosterredhat.com
#     zone: test
#     apm-number: 1234
# groupname:
#   admin_group: pa_admins  
#   edit_group:  
#   view_group:  
# resourceQuota:
#   limits_cpu: 250m
#   limits_memory: 1Gi
#   requests_cpu: 200m
#   requests_memory: 500Mi
#   persistentvolumeclaims: 5
#   limits_ephemeral_storage: 4Gi
#   pods: 50
# serviceAccount:
#   create: true
#   automount: true
#   annotations: 
#   name: pipeline