# ecrUpdateRole: arn
ecrUpdateRole:
project:
  name: placeholder
  apmnum: placeholder
  # This is the name of the namespace
  # Please follow the standard as specified in confluence
  # https://confluence.service.anz/display/ANZCP/3.+Naming+Conventions
  annotations:
    # This annotation is used to comment on the resource.
    # Use this to specify why you are changing the file.
    comments: placeholder
    # Description for the OpenShift Project
    # Ask the customer to provide one if not known.
    description: placeholder
    # Display Name for the Project
    # default should be metadata.name or
    # As provided by customer
    display_name: placeholder
  labels:
    # This label is the EGRESSIP Selector.
    # check the egressip.yaml (spec.namespaceSelector)
    egress.cpaas.test/namespace: placeholder
    # Customer Tech Domain or Business Domain . Please ask customer if not provided
    domain: placeholder
    # Customer Primary Contact. Usually the Product Owner
    # Please ask customer if not provided
    primary_owner: placeholder
    # This specifies in which DC the namespace
    zone: placeholder
    # This defines which ingress the namespace should use
    # All customers should use customer specific ingress
    # Cpaas owned namespace should use default
    ingress: placeholder
    # Egress IP assigned to this namespace.
    # Check the Conflunce tracking page for the assignment
    # di1001 - https://confluence.service.anz/display/ANZCP/Egress+IP+-+di1001
    # qi1001 - https://confluence.service.anz/display/ANZCP/Egress+IP
    # This label is just for tracking purpose
    # Egress is controlled from egressip.yaml and with egress.cpaas.test/namespace
    # label on the namespace
    egressip: placeholder

groupname:
  # customer ldap groups
  admin_group: placeholder
  edit_group: placeholder
  view_group: placeholder

resourceQuota:
  # hard limit of total cpu's sumof(all pod) in the namespace
  limits_cpu: placeholder
  # hard limit of total memory sumof(all pod) in the namespace
  limits_memory: placeholder
  # hard request of total cpu's sumof(all pod) in the namespace
  # This is always match limit.cpu
  requests_cpu: placeholder
  # hard request of total memory sumof(all pod) in the namespace
  # This is always match limit.memory
  requests_memory: placeholder
  # Total number of pvc's allowed in the namespace
  persistentvolumeclaims: placeholder
  # Total size of sumof(all pods) can occupy when running
  limits_ephemeral_storage: placeholder
  # Total number of pods in a namespace
  pods: placeholder
  # Total size of sumof(all PV's) in the namespace
  #trident-ontap-mw.storageclass.storage.k8s.io/requests.storage: "50Gi"

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "cpaas-ns-template"