{{- with .Values }}
{{ if eq ( .enabled | toString) "true" }}
{{- range .checks }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncwave | default 0 | quote }}
  name: {{ .serviceAccount.name }}-{{ .namespace.name }}
  namespace: {{ .namespace.name | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
rules:
  - apiGroups:
      - operators.coreos.com
    resources:
      - clusterserviceversions
      - installplans
      - subscriptions
    verbs:
      - get
      - list
      - patch
{{- end }}
{{- end }}
{{- end }}
