{{- with .Values }}
{{ if eq ( .enabled | toString) "true" }}
{{- range .checks }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .serviceAccount.name | quote }}
  namespace: {{ .namespace.name | quote }}
  labels:
    {{- include "common.labels" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .syncwave | default 0 | quote }}
{{- end }}
{{- end }}
{{- end }}
