namespace: rhsso-operator
clientSecret: "holding"
subscription:
  channel: stable
  installPlanApproval: Manual
  name: rhsso-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: rhsso-operator.7.6.4-opr-002
realm:
  identityProviders:
    - alias: GitHub
      providerId: github
      syncMode: IMPORT
client:
  redirectUri:
  - holder


helper-status-checker:
  enabled: true
  approver: true
  checks:
    - operatorName: rhsso-operator
      subscriptionName: rhsso-operator
      namespace:
        name: rhsso-operator
      serviceAccount:
        name: "rhssh-serverless-install-check"
 