apiVersion: v2
name: jaeger-operator
description: Helm chart for deploying Red Hat OpenShift Jaeger Operator
type: application
version: 0.1.1
appVersion: "1.57"
dependencies:
  - name: helper-operator
    version: ~1.1.0
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
  - name: helper-status-checker
    version: ~4.1.2
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
    condition: helper-status-checker.enabled
