serverlessLogicOperator:
  # -- whether the operator should be deployed by the chart
  enabled: true
  subscription:
    # -- namespace where the operator should be deployed
    namespace: openshift-serverless-logic
    spec:
      # -- channel of an operator package to subscribe to
      channel: alpha
      # --  whether the update should be installed automatically
      installPlanApproval: Manual
      # -- name of the operator package
      name: logic-operator-rhel8
      # --  name of the catalog source
      source: redhat-operators
      sourceNamespace: openshift-marketplace
      # -- The initial version of the operator, must match CRDs installed by the chart
      startingCSV: logic-operator-rhel8.v1.36.0

# Operator configuration
operatorName: gpu-operator-certified
operatorNamespace: nvidia-gpu-operator
operatorChannel: stable
operatorSource: certified-operators
operatorSourceNamespace: openshift-marketplace
operatorInstallPlanApproval: Manual

helper-status-checker:
  enabled: true
  approver: true
  checks:
    - operatorName: gpu-operator-certified
      subscriptionName: gpu-operator-certified
      namespace:
        name: nvidia-gpu-operator
      serviceAccount:
        name: "gpu-install-check"
    - operatorName: nfd
      approver: false
      subscriptionName: nfd
      namespace:
        name: openshift-nfd
      serviceAccount:
        name: "gpu-nfd-install-check"