apiVersion: v2
name: servicemesh-operator
description: Helm chart for deploying Red Hat OpenShift Service Mesh Operator
type: application
version: 0.5.0
appVersion: "2.5"
dependencies:
  - name: helper-operator
    version: ~1.1.0
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
  - name: helper-status-checker
    version: 4.3.7
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
    condition: helper-status-checker.enabled
