apiVersion: v2
name: web-terminal-operator
description: Helm chart for deploying Red Hat OpenShift Web Terminal Operator
type: application
version: 0.1.1
appVersion: "1.9"
dependencies:
  - name: helper-operator
    version: ~1.1.0
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
  - name: helper-status-checker
    version: ~4.1.6
    repository: https://rosa-hcp-dedicated-vpc.github.io/helm-repository/
    condition: helper-status-checker.enabled
