apiVersion: v1
kind: Namespace
metadata:
  annotations:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    openshift.io/display-name: 'overprovisioning'
  labels:
    app: overprovisioning
  name: overprovisioning
